name: Gemini AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gemini AI Code Reviewer
        uses: truongnh1992/gemini-ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.AI_API_KEY }}
          GEMINI_MODEL: gemini-2.5-flash
          EXCLUDE: "*.md,*.txt,package-lock.json,*.yml,*.yaml"